import pandas as pd

felder = [
    "Los",
    "Badstraße",
    "Gemeinschaft 1",
    "Turmstraße",
    "Einkommenssteuer",
    "Südbahnhof",
    "Chausseestraße",
    "Ereignis 1",
    "Elisenstraße",
    "Poststraße",
    "Gefängnis",
    "Seestraße",
    "Elektrizitätswerk",
    "Hafenstraße",
    "Neue Straße",
    "Westbahnhof",
    "Münchner Straße",
    "Gemeinschaft 2",
    "Wiener Straße",
    "Berliner Straße",
    "Frei Parken",
    "Theaterstraße",
    "Ereignis 2",
    "Museumstraße",
    "Opernplatz",
    "Nordbahnhof",
    "Lessingstraße",
    "Schillerstraße",
    "Wasserwerk",
    "Goethestraße",
    "Gehe in Gefängnis",
    "Rathausplatz",
    "Hauptstraße",
    "Gemeinschaft 3",
    "Bahnhofstraße",
    "Hauptbahnhof",
    "Ereignis 3",
    "Parkstraße",
    "Zusatzsteuer",
    "Schlossallee",
]

csv = pd.DataFrame({"Straßen": felder})
csv.to_csv("ergebnisse.csv", index=False)
